#!/usr/bin/python
import digitalocean
import sys
import re
import json 
import os

def main(argv):
	config_file = open(os.path.dirname(os.path.realpath(__file__)) + os.path.sep + 'config')
	config = json.load(config_file)
	
	try:
		manager = digitalocean.Manager()
		manager.auth(config["auth"]["client_id"], config["auth"]["api_key"])
			
		if len(argv) == 0 or argv[0] == "help":
			print(digitalocean.util.manual())
		elif argv[0] == "list":
			if len(argv) == 1:
				manager.listDroplets()
			else:
				manager.listDroplet(argv[1])
		elif argv[0] == "start" and len(argv) == 2:
			manager.startDroplet(argv[1])
			
		elif argv[0] == "stop" and len(argv) == 2:
			manager.stopDroplet(argv[1])
		elif argv[0] == "stop" and len(argv) == 3 and argv[1] in ["--force", "-f"]:
			manager.poweroffDroplet(argv[2])
			
		elif argv[0] == "restart" and len(argv) == 2:
			manager.restartDroplet(argv[1])
		else:
			print(digitalocean.util.manual())
	except Exception as e:
		print(e)
if __name__ == "__main__":
   main(sys.argv[1:])